KnockoutMvcDemo/Controllers/BigDataController.cs
using System.Web.Mvc;
using KnockoutMvcDemo.Models;

namespace KnockoutMvcDemo.Controllers
{
  public class BigDataController : BaseController
  {
    public ActionResult Index()
    {
      InitializeViewBag("Big data");
      return View();
    }

    public ActionResult InitialData(BigDataModel model)
    {
      model.LoadData();
      return Json(model);
    }
  }
}

KnockoutMvcDemo/Controllers/GiftListController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using KnockoutMvcDemo.Models;

namespace KnockoutMvcDemo.Controllers
{
  public class GiftListController : BaseController
  {
    public ActionResult Index()
    {
      InitializeViewBag("Gift list");
      var model = new GiftListModel
      {
        Gifts = new List<GiftModel>
            {
              new GiftModel {Title = "Tall Hat", Price = 49.95},
              new GiftModel {Title = "Long Cloak", Price = 78.25}
            }
      };
      return View(model);
    }

    public ActionResult AddGift(GiftListModel model)
    {
      model.AddGift();
      return Json(model);
    }

    public ActionResult RemoveGift(GiftListModel model, int index)
    {
      model.RemoveGift(index);
      return Json(model);
    }

    public ActionResult Save(GiftListModel model)
    {
      model.Save();
      return Json(model);
    }
  }
}

KnockoutMvcDemo/Controllers/HomeController.cs
using System.Web.Mvc;

namespace KnockoutMvcDemo.Controllers
{
  public class HomeController : System.Web.Mvc.Controller
  {
    //
    // GET: /Home/

    public ActionResult Index()
    {      
      return View();
    }

    //
    // GET: /BrowserSupport/

    public ActionResult Links()
    {
      return View();
    }

    //
    // GET: /QuickStart/

    public ActionResult QuickStart()
    {
      return View();
    }

    //
    // GET: /Documentation/

    public ActionResult Documentation()
    {
      return View();
    }

    //
    // GET: /Intro/

    public ActionResult Introduction()
    {
      return View();
    }

    //
    // GET: /Downloads/

    public ActionResult Downloads()
    {
      return View();
    }
  }
}

KnockoutMvcDemo/Views/Home/ConceptTable.cshtml
<div class="row">
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/knockout.png")" alt="Knockout" />
    <h2 class="conceptCaption">Knockout based</h2>
    <p>Extension of the popular JavaScript library Knockout.js</p>
  </div>
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/mvc3.png")" alt="Mvc3" />
    <h2 class="conceptCaption">ASP.NET MVC</h2>
    <p>Complete integration with ASP.NET MVC3/MVC4</p>
  </div>
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/mvvm.png")" alt="MVVM" />
    <h2 class="conceptCaption">MVVM</h2>
    <p>Application is created with the help of Model-View-View Model (MVVM) pattern</p>
  </div>
</div>
<div class="row">
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/csvb.png")" alt="Expressions" />
    <h2 class="conceptCaption">C#/VB Expressions</h2>
    <p>Simple C#/VB.NET expressions defining logic of the client side behavior are automatically
      converted to JavaScript constructions</p>
  </div>
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/model.png")" alt="Model" />
    <h2 class="conceptCaption">Model on server</h2>
    <p>The model is described only once in C#/VB.NET and is stored on the server</p>
  </div>
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/intellisense.png")" alt="IntelliSense" />
    <h2 class="conceptCaption">IntelliSense</h2>
    <p>Data binding and element generation codes are written in pure C#/VB.NET with IntelliSense
      feature</p>
  </div>
</div>
<div class="row">
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/withoutjs.png")" alt="WithoutJavaScript" />
    <h2 class="conceptCaption">Without JavaScript code</h2>
    <p>Even the most complicated client-oriented application can be developed without
      a single line of JavaScript!</p>
  </div>
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/smalljs.png")" alt="SmallJavaScript" />
    <h2 class="conceptCaption">Small JavaScript library</h2>
    <p>Less JavaScript code (compressed version of Knockout takes about 40Kb)</p>
  </div>
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/ajax.png")" alt="Ajax" />
    <h2 class="conceptCaption">Ajax</h2>
    <p>Logic of work with the model is described on the server and requests are sent to
      the server via ajax queries without page re-load</p>
  </div>
</div>
<div class="row">
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/syntax.png")" alt="Syntax" />
    <h2 class="conceptCaption">Nice syntax</h2>
    <p>Short laconic syntax used to describe views – easy-to-write and easy-to-read</p>
  </div>
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/development.png")" alt="Simple development" />
    <h2 class="conceptCaption">Simple development</h2>
    <p>Website development is as easy as development of a common application – all logic
      of client-server interaction is hidden inside</p>
  </div>
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/dependencies.png")" alt="AlmostNoDependencies" />
    <h2 class="conceptCaption">Almost no dependencies</h2>
    <p>Minimum dependencies: Knockout.js and jQuery (the last one is necessary only for
      specific functions)</p>
  </div>
</div>
<div class="row">
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/browsers.png")" alt="SupportsAllBrowsers" />
    <h2 class="conceptCaption">Supports all browsers</h2>
    <p>Support for all popular browsers (IE&nbsp;6+, Firefox&nbsp;2+, Opera&nbsp;10+,
      Chrome, Safari)</p>
  </div>
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/compatibility.png")" alt="Full compatibility" />
    <h2 class="conceptCaption">Full compatibility</h2>
    <p>Complete compatibility with any other JavaScript libraries (jQuery, Prototype, etc.)</p>
  </div>
  <div class="span4">
    <img class="conceptImg" src="@Url.Content("~/Images/Concepts/documentation.png")" alt="Detailed documentation" />
    <h2 class="conceptCaption">Detailed documentation</h2>
    <p>API docs, live examples</p>
  </div>
</div>
<style scoped="scoped">
  .conceptCaption
  {
    font-size: 170%;
    margin-top: 5px;
    margin-bottom: 5px;
  }
  .conceptImg
  {
    max-width: 60px;
    max-height: 30px;
    float: left;
    margin: 7px 10px 0px 0px;
  }
</style>

KnockoutMvcDemo/Views/Home/Downloads.cshtml
@{
  ViewBag.Title = "Downloads";
  Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="well">
  <h2>Downloads</h2>
  <a href="https://github.com/AndreyAkinshin/knockout-mvc/downloads">Binaries</a><br />
  <a href="https://github.com/AndreyAkinshin/knockout-mvc">Source and Demo (GitHub)</a><br />
  <br />
  <h2>Licence</h2>
  <p>
    The Knockout MVC is currently available for use in all personal or commercial projects
    under <a href="http://www.opensource.org/licenses/mit-license.php">MIT license</a>.
  </p>
  <br />
  <h2>Roadmap</h2>
  <p>Plans for the next version:</p>
  <ul>
    <li>Data validation</li>
    <li>Advanced translation C# to JavaScript</li>
    <li>Advanced work with partial models</li>
    <li>Special settings for variable names</li>
    <li>Special settings for <a href="http://knockoutjs.com/documentation/plugins-mapping.html">mapping-plugin</a></li>
    <li>Small additional features and minor bug fix</li>
  </ul>
</div>

KnockoutMvcDemo/Views/Home/Index.cshtml
@{
  ViewBag.Title = "Knockout MVC";
  Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="well">  
  <div style="text-align: center">
    <img src="@Url.Content("~/Images/Logo/logo180x100.png")" alt="Knockout MVC"/>
  </div>
  <h2 style="text-align: center; font-size: 20pt; margin-top: 10px; margin-bottom: 10px">
    Power of <a href="http://knockoutjs.com/">Knockout.js</a> for <a href="http://www.asp.net/mvc/mvc3">
      ASP.NET MVC</a>.</h2>
  <div style="margin-left: 50px; margin-right: 10px">
    @RenderPage(@Url.Content("~/Views/Home/ConceptTable.cshtml"))
  </div>
</div>

KnockoutMvcDemo/Views/Home/Introduction.cshtml
@{
  ViewBag.Title = "Introduction";
  Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="well">
  <h2>Introduction</h2>
  <article>
    <h3>Brief Overview</h3>
    <p><a href="http://knockoutjs.com/documentation/introduction.html">Knockout.js</a>
      - is a popular JavaScript library that allows easy creation of feature-rich applications
      based on <i>Model-View-View Model (MVVM) pattern</i>: user interface can be bound
      to a separate existing data model. And any change of the model will result in dynamic
      refresh of the interface.</p>
    <p><b>Knockout MVC</b> is a library for <a href="http://www.asp.net/mvc/mvc3">ASP.NET
      MVC3</a> , that is a wrapper for Knockout.js, that helps to move entire business
      logic to the server side: the complete JavaScript code necessary on the client side
      will be generated automatically based on the described C# (or VB.NET) model. Binding
      of the page interface to business model is done <a href="http://knockoutjs.com/documentation/observables.html#mvvm_and_view_models">
        MVVM-style</a> with the help of C#/VB.NET expressions (not separate properties,
      but expressions over them that will be translated to JavaScript code) using IntelliSense.
      If complex operations should be done to the model, it is possible to address to
      any model method on the server using one short string (ajax query will be automatically
      generated; and when the client will get the updated model, the whole interface will
      automatically refresh).</p>
    <p>Generated JavaScript code is based on Knockout.js and that is why it works under
      any browser <i>(even IE&nbsp;6)</i>. Thus, describing the whole business logic on
      the server in a single instance we get an ability to create <b>fully-featured cross-browser
        client Web application without writing a single JavaScript code!</b></p>
  </article>
  <article>
    <h3>Compatibility</h3>
    <p>Today, any serious application rarely uses only one library. And very often the
      problem of libraries compatibility arises. Knockout MVC lacks this disadvantage.
      It is always possible to add your own native Knockout-code to the existing C# code
      (<a href="@Url.Action("Index", "UserScript")">example</a>). And Knockout itself
      greatly mates with any other libraries. Knockout.js doesn’t depend on any other
      libraries; however its core hides various useful tools for work with <a href="http://www.prototypejs.org/">
        jQuery</a> (that start working when it is connected). It is possible to use other
      libraries (for example, <a href="http://www.prototypejs.org/">Prototype</a>), but
      is you use jQuery (as many other developers) you can use any jQuery plug-ins (for
      example, <a href="http://docs.jquery.com/Plugins/Validation">jQuery.Validation</a>,
      <a href="@Url.Action("Index", "GiftList")">example</a>). You can use <a href="http://requirejs.org/">
        RequireJs</a> (<a href="http://knockoutjs.com/documentation/amd-loading.html">example</a>)
      to load big scripts.</p>
    <p>Besides compatibility with third-party libraries, it’s worth to mention browser
      compatibility: Knockout MVC is completely cross-browser (since it is based on Knockout.js)
      and works fine in IE&nbsp;6+, Firefox&nbsp;2+, Opera&nbsp;10+, Chrome, Safari. You
      can get more information <a href="http://knockoutjs.com/documentation/browser-support.html">
        here</a>.</p>
  </article>
  <article>
    <h3>Motivation</h3>
    <p>Let’s consider the following popular task: we want to provide user with the ability
      to edit some data model. And some data handler logic is hosted on the server (for
      example, saving to database). We want to use ajax to send requests to server in
      order to avoid page re-load. But using ajax results in the necessity to describe
      logic on the client side that will be able to update the page based on the response.
      Besides, it is necessary to describe some part of data model processing on the client
      side using JavaScript in order to arrange good dynamic user interface (why refer
      to server each time user click a button). Let’s see what should be done to solve
      this issue without using special libraries under ASP.NET.</p>
    <p><b>Solve without libraries under ASP.NET:</b></p>
    <ul>
      <li><i class="label label-bad">[JavaScript]</i> Describe data model on the client
        side</li>
      <li><i class="label label-bad">[JavaScript]</i> Describe logic of initialization of
        edit fields</li>
      <li><i class="label label-bad">[JavaScript]</i> Describe logic of data model processing
        on the client side</li>
      <li><i class="label label-bad">[JavaScript]</i> Describe logic of data transmission
        to server (manually collect data from the necessary fields and serialize it)</li>
      <li><i class="label label-good">[C#]</i> Describe data model on the server side</li>
      <li><i class="label label-good">[C#]</i> Describe logic of de-serialization of the
        client query to the model</li>
      <li><i class="label label-good">[C#]</i> Describe logic of data model processing on
        the server</li>
      <li><i class="label label-good">[C#]</i> Describe logic of serialization of the model
        and sending new data back to the client</li>
      <li><i class="label label-bad">[JavaScript]</i> Describe logic of de-serialization
        of the response to the existing model</li>
      <li><i class="label label-bad">[JavaScript]</i> Describe logic of updating user interface
        elements according to new data</li>
    </ul>
    <p>If the model quite small, these actions are quite obvious, but if you want to add
      new property or method to the model you will need to carefully write considerable
      amount of code. Pay attention to word “carefully” &mdash; you will need to move
      many names between different implementations of one and the same model from memory.
      As to refactoring, it’s very sad &mdash; our IDE can’t help us at all. If you just
      want to rename some item, you will need to edit it multiple locations, carefull
      check complete code and entirely test it.</p>
    <p>Don’t be so sad in advance &mdash; now you have a new wonderful library! Let’s
      see what will be solution of our task with the use of Knockout MVC.</p>
    <p><b>Solve with Knockout MVC:</b></p>
    <ul>
      <li><i class="label label-good">[C#]</i> Describe data model and logic of its processing
        on the server</li>
      <li><i class="label label-good">[C#]</i> Specify what data model element corresponds
        to every interface element</li>
    </ul>
    <p>That’s all! The rest of logic will be generated automatically! Refactoring of such
      Web application won’t differ from refactoring of common C# application. You don’t
      need to remember name of any property or method – IntelliSence will help you write
      its name correctly. And even if there is an error, you will know it on the compilation
      stage. If some simple logic should be executed on both client side and server side
      (for example, validation of form fields), it is written in C# just once (then this
      code will be converted to JavaScript).</p>
  </article>
  <article>
    <h3>Simple Sample</h3>
    <p>Now let’s have a look at syntax. All data bindings are described in the following
      way:</p>
    <pre class="prettyprint lang-cs">&#64;ko.Html.TextBox(m => m.A)</pre>
    <p>As you can see, when creating data bindings we transmit an expression indicating
      exact data model property we can bind to. As we do it in C#, we have fully-features
      IntelliSense that will give us a clue about available properties and their types:</p>
    <img src="@Url.Content("~/Images/ScreenShots/screens-intellisense.png")" alt="screens-intellisense" style="border: 1px solid black"/>
    <p>As a result, these constructions will be transformed to html with Knockout code:</p>
    <pre class="prettyprint lang-html">&lt;input data-bind="value : A" /&gt;</pre>
    <p>The following sample shows that we can create data bindings not only for common
      objects and not only to specific properties, but to bind complex constructions to
      expressions (the first line is Razor code, the second line is html it is automatically
      converted to):</p>
    <pre class="prettyprint lang-cs">
<span class="nocode">Razor: </span>&#64;using (ko.If(model => model.Condition1 &amp;&amp; model.Condition2))
<span class="nocode">Html: &nbsp;</span>&lt;!-- ko if: Condition1()&amp;&amp;Condition2() --&gt;
</pre>
    <p>The complete list of syntax constructions that can be used is available in the
      <a href="@Url.Action("Documentation", "Home")">documentation</a>.</p>
  </article>
  <article>
    <h3>Other samples</h3>
    <p>To get deeper understanding of the development process when using Knockout MVC,
      we took some samples from the official site and re-wrote them in C#. Here is what
      we got as a result:</p>
    <table class="exampleTable">
      <tr>
        <th>Knockout.js</th>
        <th>Knockout MVC</th>
      </tr>
      <tr>
        <td>
          <a href="http://knockoutjs.com/examples/helloWorld.html">Hello world</a>
        </td>
        <td>
          @Html.ActionLink("Hello world", "Index", "HelloWorld")
        </td>
      </tr>
      <tr>
        <td>
          <a href="http://knockoutjs.com/examples/clickCounter.html">Click counter</a>
        </td>
        <td>
          @Html.ActionLink("Click counter", "Index", "ClickCounter")
        </td>
      </tr>
      <tr>
        <td>
          <a href="http://knockoutjs.com/examples/simpleList.html">Simple list</a>
        </td>
        <td>
          @Html.ActionLink("Simple list", "Index", "SimpleList")
        </td>
      </tr>
      <tr>
        <td>
          <a href="http://knockoutjs.com/examples/betterList.html">Better list</a>
        </td>
        <td>
          @Html.ActionLink("Better list", "Index", "BetterList")
        </td>
      </tr>
      <tr>
        <td>
          <a href="http://knockoutjs.com/examples/controlTypes.html">Control types</a>
        </td>
        <td>
          @Html.ActionLink("Control types", "Index", "ControlTypes")
        </td>
      </tr>
      <tr>
        <td>
          <a href="http://knockoutjs.com/examples/collections.html">Working with coolection</a>
        </td>
        <td>
          @Html.ActionLink("Working with collection", "Index", "Collections")
        </td>
      </tr>
      <tr>
        <td>
          <a href="http://knockoutjs.com/examples/contactsEditor.html">Contacts editor</a>
        </td>
        <td>
          @Html.ActionLink("Contacts editor", "Index", "ContactsEditor")
        </td>
      </tr>
      <tr>
        <td>
          <a href="http://knockoutjs.com/examples/cartEditor.html">Cart editor</a>
        </td>
        <td>
          @Html.ActionLink("Cart editor", "Index", "CartEditor")
        </td>
      </tr>
      <tr>
        <td>
          <a href="http://blog.stevensanderson.com/2010/07/12/editing-a-variable-length-list-knockout-style/">
            Gift list</a>
        </td>
        <td>
          @Html.ActionLink("Gift list", "Index", "GiftList")
        </td>
      </tr>
    </table>
    <p>Besides, there are a number of samples created to demonstrate some Knockout MVC
      features:</p>
    <ul>
      <li>@Html.ActionLink("Region (if, foreach, with)", "Index", "Region")</li>
      <li>@Html.ActionLink("Complex bindings (style)", "Index", "ComplexBinding")</li>
      <li>@Html.ActionLink("Parameters to server", "Index", "ParametersToServer")</li>
      <li>@Html.ActionLink("User script", "Index", "UserScript")</li>
      <li>@Html.ActionLink("Combine context", "Index", "CombineContext")</li>
      <li>@Html.ActionLink("Inner computed properties", "Index", "InnerComputed")</li>
      <li>@Html.ActionLink("Big data (with lazy loading)", "Index", "BigData")</li>
    </ul>
  </article>
  <article>
    <h3>License</h3>
    <p>The Knockout MVC is currently available for use in all personal or commercial projects
      under <a href="http://www.opensource.org/licenses/mit-license.php">MIT license</a>.</p>
  </article>
  <article>
    <h3>Resume</h3>
    <div style="margin-left: 50px; margin-right: 10px">
      @RenderPage(@Url.Content("~/Views/Home/ConceptTable.cshtml"))
    </div>
  </article>
</div>
<style scoped="scoped">
  .exampleTable
  {
    border-spacing: 5px;
    text-align: center;
  }
  .exampleTable td
  {
    padding-left: 10px;
    padding-right: 10px;
  }
  .label-good
  {
    background-color: #468847;
  }
  .label-bad
  {
    background-color: #b94a48;
  }
</style>

KnockoutMvcDemo/Views/Home/Links.cshtml
@{
  ViewBag.Title = "Links";
  Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="well">
  <h2>Links</h2>
  <h3>Knockout</h3>
  <ul>
    <li><a href="http://knockoutjs.com/">Knockout.js</a> &#8212; official site</li>    
    <li><a href='http://www.knockmeout.net'>Knock Me Out</a> &#8212; Ryan Niemeyer&#8217;s
      excellent blog containing ideas, thoughts, and discussion about KnockoutJS and related
      technologies</li>
    <li><a href='http://www.pluralsight-training.net/microsoft/Courses/TableOfContents?courseName=knockout-mvvm'>
      PluralSight Knockout.js training course</a> &#8212; Online videos - John Papa provides
      almost 5 hours of in-depth content (<a href='http://johnpapa.net/komvvm'>more info</a>)</li>
    <li><a href='http://blog.stevensanderson.com/2010/07/12/editing-a-variable-length-list-knockout-style/'>
      Editing a variable-length list, Knockout-style</a> &#8212; Steve Sanderson shows
      the advantages of using Knockout with ASP.NET MVC</li>
    <li><a href='http://github.com/carlhoerberg/knockout-websocket-example'>Knockout+WebSockets</a>
      &#8212; Carl Hörberg combines Knockout, Sinatra, SQLite, and WebSockets to implement
      realtime forms collaboration</li>
    <li><a href='http://geeks.aretotally.in/log4play-log4j-ui-mashed-up-with-play-framework-knockout-js-and-websockets'>
      Log4Play: Log4j Live Streaming with Play Framework, Knockout.js and WebSockets</a>
      &#8212; Felipe Oliveira creates a realtime server log with KO and WebSockets</li>
    <li><a href='https://github.com/SteveSanderson/knockout/wiki/Recipes'>Wiki - Recipes</a>
      &#8212; User contributed recipes and examples</li>
    <li><a href='https://github.com/SteveSanderson/knockout/wiki/Plugins'>Wiki - Plugins</a>
      &#8212; User contributed list of plugins</li>
  </ul>
  <h3>ASP.NET MVC</h3>
  <ul>
    <li><a href="http://www.asp.net/mvc/mvc3">ASP.NET MVC3</a> &#8212; official site</li>
    <li><a href="http://www.asp.net/mvc/mvc4">ASP.NET MVC4</a> &#8212; official site</li>
    <li><a href="http://www.asp.net/mvc/mvc3#BM_TheRazorViewEngine">Razor view engine</a></li>
  </ul>
  <h3>Kncokout MVC</h3>
  <ul>
    <li><a href="https://github.com/AndreyAkinshin/knockout-mvc">Project on GitHub</a></li>
  </ul>
</div>

KnockoutMvcDemo/Views/Home/QuickStart.cshtml
@{
  ViewBag.Title = "Quick start";
  Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="well">
  <h2>Quick start</h2>
  <ul>
    <li>Add reference to <code>PerpetuumSoft.Knockout</code></li>
    <li>Add next line to <code>Application_Start()</code> in <code>Global.asax</code>:
      <pre class="prettyprint lang-cs">
ModelBinders.Binders.DefaultBinder = new KnockoutModelBinder();</pre>
    </li>
    <li>Add links to next js-files:
      <pre class="prettyprint lang-xml">
&lt;script src="@Url.Content("~/Scripts/jquery-1.7.2.min.js")" type="text/javascript"&gt;&lt;/script&gt;
&lt;script src="@Url.Content("~/Scripts/knockout-2.1.0.js")" type="text/javascript"&gt;&lt;/script&gt;
&lt;script src="@Url.Content("~/Scripts/knockout.mapping-latest.js")" type="text/javascript"&gt;&lt;/script&gt;
&lt;script src="@Url.Content("~/Scripts/perpetuum.knockout.js")" type="text/javascript"&gt;&lt;/script&gt;</pre>
    </li>
    <li>Use next template for view:
      <pre class="prettyprint lang-cs">
&#64;using PerpetuumSoft.Knockout
&#64;model &lt;!-- You model --&gt;
&#64;{
  var ko = Html.CreateKnockoutContext();
}
&lt;!-- Your page --&gt;

&#64;ko.Apply(Model)</pre>
    </li>
    <li>Inherit your controller from <code>KnockoutController:</code>
      <pre class="prettyprint lang-cs">
public class FooController : KnockoutController {
  public ActionResult Index()
  {    
    return View();
  }
}</pre>
    </li>
  </ul>
</div>